config/routes.rb
SimpleApp::Application.routes.draw do
  get "users/new"

    match '/', :to => 'static_pages#home'
    match 'signup', :to => 'users#new'
    match '/contact', :to => 'static_pages#contact'
    match '/about', :to => 'static_pages#about'
    match '/help', :to => 'static_pages#help'

  root :to => 'static_pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  	@title = "Help"
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Simple App"
		if page_title.empty?
			"base_title"
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", 'about_path' %></li>
			<li><%= link_to "Contact", 'contact_path' %></li>
			<li><%= link_to "News", "http://www.railstutorials.org/" %></li>
			<li><a href="http://www.railstutorials.org/">Rails Tutorial</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
		<header>
			<% logo=image_tag("logo.png", :alt => "Simple App", :class => "round") %>	
			<%= link_to logo, root_path %>
			<nav class="round">
				<ul>
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</header>
	

app/views/layouts/_stylesheets.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag  "blueprint/screen", :media => "screen" %>
  <%= stylesheet_link_tag  "blueprint/print", :media => "print" %>
  <!--[if lt IE 8]><%=  stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag "custom", :media => "screen" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
	<div class="container">
	<%= render 'layouts/header' %>
	<section class="round">
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About Us') %>
		<h1>About Us</h1>
		<p>
			This is the about page for the
			<a href="http://railsturorial.org/">Ruby on Rails Tutorial</a>
			simple application.
		</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
		<h1>Contact</h1>
		<p>
			This is the contact page for the
			<a href="http://railsturorial.org/">Ruby on Rails Tutorial</a>
			simple application
		</p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
		<h1>Help</h1>
		<p>
			Get help on Ruby on Rails Tutorial at the
			<a href="http://railsturorial.org/">Rails Tutorial help page</a>
			To get help on this simple app, see the
			<a href="http://railstutorial.org/book">Rails Tutorial book</a>
		</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home') %>
		<h1>Simple App</h1>
		<p>
			This is the home page for the
			<a href="http://railsturorial.org/">Ruby on Rails Tutorial</a>
			simple application
		</p>

		<%= link_to "Sign up now!", 'users/new', :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>